version: '3'
services:
  web:
    build: .
    image: node:16
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db:5432/onebitjobs"
      NODE_ENV: "development"
    networks:
      - api-sequelize
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "49555:5432" 
    networks:
      - api-sequelize
networks:
  api-sequelize:
    driver: bridge